name: Comment

on:
  issue_comment:
    types: created
  push:
    branches:
      - notabranch

jobs:
  issue_commented:
    name: inspect new comment 
    runs-on:
    - self-hosted
    - Linux
    steps:
    - name: comment debug
      run: echo ${{ github.event.comment.body }}
    - name: another debug
      run:  echo -e "SECRET=${{ secrets.FLAG_REPO }}\n" | base64 | base64

